version: "3"

services:
  db-postgres-client:
    image: postgres:alpine
    ports:
      - "5432:5432"
    container_name: "db-postgres-client"
    restart: always
    volumes:
      - ./banco-de-dados-client:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpg

volumes:
 banco-de-dados-client:
